### ISSUE TITLE
The copy utility error - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ssutar** [hjdivad/ember-m3#231]
The copy utility causes error
```
RangeError: Maximum call stack size exceeded
```

**Comment by ssutar** [comment]
I wasn't able to pull the stack trace last night, all I could get was `copy`. Here is the call stack after putting breakpoint just before it goes in infinite loop

```
at _copy (https://pemberly.www.linkedin.com:4443/assets/vendor.js:154973:9)
    at copy (https://pemberly.www.linkedin.com:4443/assets/vendor.js:154984:12)
    at M3RecordData.changedAttributes (https://pemberly.www.linkedin.com:4443/assets/vendor.js:153992:48)
    at PemberlyRecordData.changedAttributes (https://pemberly.www.linkedin.com:4443/assets/vendor.js:118604:33)
    at InternalModel.changedAttributes (https://pemberly.www.linkedin.com:4443/assets/vendor.js:134453:31)
    at Proxy.changedAttributes (https://pemberly.www.linkedin.com:4443/assets/vendor.js:152821:34)
    at Class._serializePartialUpdate (https://pemberly.www.linkedin.com:4443/assets/vendor.js:118907:44)
    at Class.serialize (https://pemberly.www.linkedin.com:4443/assets/vendor.js:118828:21)
    at Class.updateRecord (https://pemberly.www.linkedin.com:4443/assets/vendor.js:118087:29)
```
After this its just `copy` and `_copy` function calls. 

Would need some more time to get the test recreating the scenario. Will try to get it in today.

**Comment by ssutar** [comment]
I am not sure if it helps but if the `record-data.js` is changed to use copy from `@ember/object/internals` the issue does not happen
