### ISSUE TITLE
M3 uses _identityMap._map in a test

### ISSUE THREAD

**Issue by runspired** [hjdivad/ember-m3#301]
I'm not sure yet what a public way of replicating this test would be, but it likely plays into better APIs for the inspector as well. PR https://github.com/emberjs/data/pull/6246 refactors the identityMap restricting access to it while things are redone with identifiers.

https://github.com/hjdivad/ember-m3/blob/9de75bcebd33f2c52f9fc2865080f83e403ab725/tests/unit/store-test.js#L70

**Comment by rwjblue** [comment]
ember-data@3.12.0 was published yesterday and is now the latest stable version. This issue is now blocking CI of ember-m3:

```
not ok 304 Chrome 76.0 - [32 ms] - unit/store/global-cache: records are added to, and unloaded from, the global m3 cache
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read property '_map' of undefined
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:13722:60)
                at runTest (http://localhost:7357/assets/test-support.js:5670:30)
                at Test.run (http://localhost:7357/assets/test-support.js:5656:6)
                at http://localhost:7357/assets/test-support.js:5883:12
                at processTaskQueue (http://localhost:7357/assets/test-support.js:5249:24)
                at http://localhost:7357/assets/test-support.js:5253:8
        message: >
            Died on test #1     at Object.<anonymous> (http://localhost:7357/assets/tests.js:13695:21)
                at processModule (http://localhost:7357/assets/test-support.js:3817:16)
                at module$1 (http://localhost:7357/assets/test-support.js:3842:4)
                at Module.callback (http://localhost:7357/assets/tests.js:13629:21)
                at Module.exports (http://localhost:7357/assets/vendor.js:7686:32)
                at requireModule (http://localhost:7357/assets/vendor.js:7607:18)
                at TestLoader.<anonymous> (http://localhost:7357/assets/test-support.js:43941:11): Cannot read property '_map' of undefined
        negative: >
            false
        browser log: |
```
