### ISSUE TITLE
Failure in removing unloaded records from the cache with ember-data@3.12

### ISSUE THREAD

**Issue by rwjblue** [hjdivad/ember-m3#342]
This test is failing when ran against ember-data@3.12.0:

https://github.com/hjdivad/ember-m3/blob/e994d3523d8650039bc1053b1174d442000887b3/tests/unit/model-test.js#L299-L327

The failure is:

```
not ok 21 Chrome 76.0 - [128 ms] - unit/model: global m3 cache removes unloaded records
    ---
        actual: >
            [object Object]
        expected: >
            null
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:1818:14)
                at runTest (http://localhost:7357/assets/test-support.js:5670:30)
                at Test.run (http://localhost:7357/assets/test-support.js:5656:6)
                at http://localhost:7357/assets/test-support.js:5883:12
                at processTaskQueue (http://localhost:7357/assets/test-support.js:5249:24)
                at http://localhost:7357/assets/test-support.js:5253:8
        message: >
            global m3 cache removed unloaded record
        negative: >
            false
        browser log: |
    ...
```

This failure seems fundamental and suggests that we are not properly removing unloaded records as of ember-data@3.12.0.

**Comment by runspired** [comment]
This is because M3 is using a private API for the secondary cache that needs updated (see Igor's branch)
